import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';

const $=s=>document.querySelector(s),canvas=$('#game'),placeEl=$('#place'),timerEl=$('#timer'),hint=$('#hint'),countdown=$('#countdown'),restart=$('#restart');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer:coarse)').matches?1.45:1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color('#cbd8ee');scene.fog=new THREE.Fog('#cbd8ee',58,155);const camera=new THREE.PerspectiveCamera(48,1,.1,220);
scene.add(new THREE.HemisphereLight('#fff8e8','#819a83',2.1));const sun=new THREE.DirectionalLight('#fff6da',3.2);sun.position.set(-22,38,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=38;sun.shadow.camera.bottom=-38;scene.add(sun);
const course=new THREE.Group();scene.add(course);const obstacles=[],racers=[],particles=[],reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,lanes=[-7.5,-2.5,2.5,7.5],colors=['#f19abc','#f7cb65','#84d59a','#76c9e8'];
const mat=(color,rough=.82)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:0});function box(w,h,d,color,x,y,z,group=course){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;group.add(o);return o}
box(22,.7,142,'#fff5df',0,-.42,-48);lanes.forEach((x,i)=>{box(4.7,.12,136,colors[i],x,.02,-48);for(let z=17;z>-116;z-=7)box(4.2,.025,.08,'#ffffff',x,.095,z)});box(.65,1.15,142,'#f7f0e4',-11.3,.35,-48);box(.65,1.15,142,'#f7f0e4',11.3,.35,-48);for(let z=18;z>-117;z-=12){box(.35,.35,.35,'#f4b7cd',-11.25,1.2,z);box(.35,.35,.35,'#9cd9e8',11.25,1.2,z)}
[-9,-43,-78].forEach((z,row)=>{for(let i=0;i<2;i++){const mesh=box(3.8,1.9,2.5,row%2?'#a8d7ef':'#ffc09b',0,1,z);obstacles.push({kind:'slider',mesh,z,row,phase:i*Math.PI,speed:.65+row*.09})}});[-26,-61,-96].forEach((z,row)=>{const g=new THREE.Group();g.position.set(0,.55,z);course.add(g);box(1.1,2.7,1.1,'#fff1c8',0,1.05,0,g);box(18,.62,.78,row%2?'#f493b8':'#8bd4b3',0,1.35,0,g);obstacles.push({kind:'spinner',mesh:g,z,row,speed:(row%2?-.7:.78)+row*.08})});
box(22,.12,1.1,'#fff',0,.12,-112);for(let x=-10;x<10;x+=2)box(1.05,.14,1.2,((x+10)/2)%2?'#32474f':'#fff',x+.55,.19,-112);box(1.1,6,1.1,'#ffedb8',-10.5,3,-113);box(1.1,6,1.1,'#ffedb8',10.5,3,-113);box(22,1,1,'#f08eb4',0,6,-113);[12,-20,-54,-88].forEach((z,i)=>box(21.3,.035,.45,['#fff0ba','#c7f0d0','#c6e8fa','#f7bfd4'][i],0,.14,z));

function fallbackCharacter(color){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.48,.65,7,12),mat(color,.65));body.position.y=1;body.castShadow=true;g.add(body);const eyeMat=mat('#243238');[-.18,.18].forEach(x=>{const e=new THREE.Mesh(new THREE.SphereGeometry(.055,8,8),eyeMat);e.position.set(x,1.3,.44);g.add(e)});return g}
function makeRacer(name,color,lane,isPlayer=false){const root=new THREE.Group();root.position.set(lanes[lane],.1,15+lane*.65);scene.add(root);const visual=fallbackCharacter(color);root.add(visual);const shadow=new THREE.Mesh(new THREE.CircleGeometry(.55,20),new THREE.MeshBasicMaterial({color:'#43515d',transparent:true,opacity:.18,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.015;root.add(shadow);const r={name,root,visual,shadow,isPlayer,lane,targetX:lanes[lane],vx:0,vz:0,vy:0,y:0,grounded:true,stun:0,tumble:0,carriedBy:null,carrying:null,throwTime:0,checkpoint:15,finished:false,finishTime:0,aiPhase:Math.random()*9};racers.push(r);return r}
const player=makeRacer('You','#f7a8c8',1,true);makeRacer('Mint BOT','#8ed7ab',0);makeRacer('Sky BOT','#84cbe5',2);makeRacer('Honey BOT','#f3c665',3);
function chosenModel(){const files={goril:'goril-motion-v3.glb',friendsie_1:'friends/friendsie_1.glb',friendsie_100:'friends/friendsie_100.glb',friendsie_404:'friends/friendsie_404.glb',friendsie_500:'friends/friendsie_500.glb',friendsie_777:'friends/friendsie_777.glb'};let id='goril';for(const v of[3,2,1])try{const d=JSON.parse(localStorage.getItem('67park.character.v'+v)),c=v===1?d?.id:d?.base;if(files[c]){id=c;break}}catch{}return`../models/${files[id]}`}
new GLTFLoader().load(chosenModel(),gltf=>{const model=gltf.scene,b=new THREE.Box3().setFromObject(model),size=b.getSize(new THREE.Vector3()),center=b.getCenter(new THREE.Vector3()),scale=1.72/Math.max(.01,size.y);model.scale.setScalar(scale);model.position.set(-center.x*scale,-b.min.y*scale,-center.z*scale);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});player.visual.clear();player.visual.add(model)},undefined,()=>{});

const input={x:0,z:0,jump:false,grab:false},keys=new Set(),qaMode=new URLSearchParams(location.search).has('qa');let started=false,startAt=0,ended=false,cameraYaw=0,cameraPitch=.34,drag=null,qaStage=0;
hint.textContent=matchMedia('(pointer:coarse)').matches?'Reach the finish · GRAB lifts and throws rivals':'WASD · Space jump · E grab / throw';
addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;keys.add(e.code);if(e.code==='Space'){e.preventDefault();input.jump=true}if(e.code==='KeyE'||e.code==='KeyF')input.grab=true});addEventListener('keyup',e=>keys.delete(e.code));function updateKeyboard(){input.x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);input.z=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)}
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0&&e.button!==2)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;cameraYaw-=dx*.006;cameraPitch=THREE.MathUtils.clamp(cameraPitch+dy*.004,.12,.66)});canvas.addEventListener('pointerup',e=>{if(drag?.id===e.pointerId)drag=null});
const stick=$('#stick'),knob=$('#knob');let stickPointer=null;function moveStick(e){const r=stick.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);input.x=Math.cos(a)*m/42;input.z=-Math.sin(a)*m/42;knob.style.transform=`translate(${Math.cos(a)*m}px,${Math.sin(a)*m}px)`}stick.addEventListener('pointerdown',e=>{stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);moveStick(e)});stick.addEventListener('pointermove',e=>{if(stickPointer===e.pointerId)moveStick(e)});function endStick(e){if(stickPointer!==e.pointerId)return;stickPointer=null;input.x=input.z=0;knob.style.transform='translate(0,0)'}stick.addEventListener('pointerup',endStick);stick.addEventListener('pointercancel',endStick);$('#jump').addEventListener('pointerdown',e=>{e.preventDefault();input.jump=true});$('#grab').addEventListener('pointerdown',e=>{e.preventDefault();input.grab=true});restart.addEventListener('click',()=>location.reload());

function burst(pos,color){for(let i=0;i<(reduced?3:8);i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.07,6,6),new THREE.MeshBasicMaterial({color,transparent:true}));m.position.copy(pos).add(new THREE.Vector3(0,1,0));scene.add(m);particles.push({m,v:new THREE.Vector3((Math.random()-.5)*4,Math.random()*3+1,(Math.random()-.5)*4),life:.45})}}
function hitRacer(r,power=1,dx=0,dz=1){if(r.stun>0||r.carriedBy||r.finished)return;r.stun=reduced?.32:.68;r.tumble=0;r.vx=dx*5.5*power;r.vz=dz*5.5*power;r.vy=3.2*power;r.grounded=false;burst(r.root.position,'#fff4c4');if(qaMode)canvas.dataset.qaCollision='pass'}
function grabOrThrow(){if(player.stun>0||player.finished)return;if(player.carrying){const r=player.carrying;player.carrying=null;r.carriedBy=null;r.throwTime=.9;r.vx=Math.sin(cameraYaw)*10;r.vz=-Math.cos(cameraYaw)*10-3;r.vy=5;r.grounded=false;r.stun=.7;burst(r.root.position,'#ffefae');hint.textContent=`${r.name} thrown!`;setTimeout(()=>hint.classList.add('hide'),900);return}let best=null,dist=2.35;for(const r of racers){if(r===player||r.carriedBy||r.finished)continue;const d=player.root.position.distanceTo(r.root.position);if(d<dist){dist=d;best=r}}if(best){player.carrying=best;best.carriedBy=player;best.stun=0;best.vx=best.vy=best.vz=0;hint.textContent=`Holding ${best.name} · Press GRAB to throw`;hint.classList.remove('hide')}}
function obstacleHit(r,time){for(const o of obstacles){if(o.kind==='slider'){const x=Math.sin(time*o.speed+o.phase+o.row)*7.2;o.mesh.position.x=x;if(Math.abs(r.root.position.z-o.z)<1.55&&Math.abs(r.root.position.x-x)<2.45){const side=Math.sign(r.root.position.x-x)||1;hitRacer(r,1,side,.25);return}}else{o.mesh.rotation.y=time*o.speed;const dx=r.root.position.x,dz=r.root.position.z-o.z,angle=-o.mesh.rotation.y,c=Math.cos(angle),s=Math.sin(angle),lx=dx*c-dz*s,lz=dx*s+dz*c;if(Math.abs(lx)<9.4&&Math.abs(lz)<.72){const tang=Math.sign(lx||1);hitRacer(r,1.08,Math.cos(o.mesh.rotation.y)*tang,-Math.sin(o.mesh.rotation.y)*tang);return}}}}
function updateRacer(r,dt,time){if(r.finished)return;if(r.carriedBy){const p=r.carriedBy.root.position;r.root.position.set(p.x,p.y+2.25,p.z);r.root.rotation.set(0,time*4,Math.sin(time*6)*.08);return}r.root.rotation.x=r.root.rotation.z=0;if(r===player){updateKeyboard();if(qaMode)input.z=1;if(input.grab){input.grab=false;grabOrThrow()}}let mx=0,mz=-1,speed=6.4;if(r.isPlayer){mx=input.x;mz=-input.z;if(Math.hypot(mx,mz)>.05){const c=Math.cos(cameraYaw),s=Math.sin(cameraYaw),wx=mx*c-mz*s,wz=mx*s+mz*c;mx=wx;mz=wz}speed=keys.has('ShiftLeft')?8.2:6.8}else{r.aiPhase+=dt;const dodge=Math.sin(time*.65+r.aiPhase)*1.5;r.targetX=THREE.MathUtils.lerp(r.targetX,lanes[r.lane]+dodge,dt*.45);mx=THREE.MathUtils.clamp((r.targetX-r.root.position.x)*.7,-1,1);mz=-1;speed=5.7+Math.sin(r.aiPhase)*.35}
if(r.stun>0){r.stun=Math.max(0,r.stun-dt);r.tumble+=dt*(reduced?4:10);r.visual.rotation.x=r.tumble;r.visual.rotation.z=Math.sin(r.tumble)*.45;r.visual.position.y=.82+Math.sin(r.tumble)*.08}
else{r.visual.rotation.x=THREE.MathUtils.lerp(r.visual.rotation.x,0,Math.min(1,dt*13));r.visual.rotation.z=THREE.MathUtils.lerp(r.visual.rotation.z,0,Math.min(1,dt*13));const len=Math.hypot(mx,mz)||1;r.vx=THREE.MathUtils.lerp(r.vx,mx/len*speed,Math.min(1,dt*10));r.vz=THREE.MathUtils.lerp(r.vz,mz/len*speed,Math.min(1,dt*10));if(r.isPlayer&&input.jump&&r.grounded){r.vy=6.4;r.grounded=false}if(Math.hypot(mx,mz)>.08)r.root.rotation.y=Math.atan2(mx,mz)}input.jump=false;r.vy-=15.5*dt;r.root.position.x+=r.vx*dt;r.root.position.z+=r.vz*dt;r.y+=r.vy*dt;if(r.y<=0){r.y=0;r.vy=0;r.grounded=true}r.root.position.y=r.y+.1;r.root.position.x=THREE.MathUtils.clamp(r.root.position.x,-10.35,10.35);r.throwTime=Math.max(0,r.throwTime-dt);if(r.stun<=0)r.visual.position.y=Math.sin(time*11+r.aiPhase)*Math.min(.07,Math.hypot(r.vx,r.vz)*.009);obstacleHit(r,time);if(r.root.position.z<-112){r.finished=true;r.finishTime=performance.now()-startAt;r.vx=r.vz=0;r.root.position.z=-115-(racers.filter(x=>x.finished).length-1)*1.3;if(r===player)finishRace()}}
function finishRace(){ended=true;const rank=[...racers].sort((a,b)=>a.root.position.z-b.root.position.z).indexOf(player)+1;countdown.textContent=rank===1?'YOU WIN!':`#${rank} FINISH`;countdown.classList.remove('out');restart.hidden=false}function updateHud(now){const sorted=[...racers].sort((a,b)=>a.finished!==b.finished?Number(b.finished)-Number(a.finished):a.root.position.z-b.root.position.z),rank=sorted.indexOf(player)+1;placeEl.textContent=`${rank} / 4`;const ms=Math.max(0,ended?player.finishTime:now-startAt);timerEl.textContent=`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms%60000/1000)).padStart(2,'0')}.${Math.floor(ms%1000/100)}`}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();let n=3;const countId=setInterval(()=>{n--;countdown.textContent=n>0?n:'GO!';if(n<=0){clearInterval(countId);started=true;startAt=performance.now();setTimeout(()=>countdown.classList.add('out'),380);setTimeout(()=>hint.classList.add('hide'),4300)}},700);
const clock=new THREE.Clock();function frame(){const dt=Math.min(.033,clock.getDelta()),now=performance.now(),time=now/1000;if(started&&!ended){if(qaMode&&qaStage===0){racers[1].root.position.copy(player.root.position).add(new THREE.Vector3(1,0,-.2));grabOrThrow();canvas.dataset.qaGrab=player.carrying?'pass':'fail';qaStage=1}if(qaMode&&qaStage===1&&now-startAt>700){const held=player.carrying;grabOrThrow();canvas.dataset.qaThrow=held&&!player.carrying&&held.throwTime>0?'pass':'fail';qaStage=2}racers.forEach(r=>updateRacer(r,dt,time))}else obstacles.forEach(o=>{if(o.kind==='slider')o.mesh.position.x=Math.sin(time*o.speed+o.phase+o.row)*7.2;else o.mesh.rotation.y=time*o.speed});for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.v.y-=7*dt;p.m.position.addScaledVector(p.v,dt);p.m.material.opacity=Math.max(0,p.life/.45);if(p.life<=0){scene.remove(p.m);p.m.geometry.dispose();p.m.material.dispose();particles.splice(i,1)}}const focus=player.root.position.clone().add(new THREE.Vector3(0,1.2,0)),dist=8.4,off=new THREE.Vector3(Math.sin(cameraYaw)*dist,3.2+cameraPitch*3.2,Math.cos(cameraYaw)*dist);camera.position.lerp(focus.clone().add(off),1-Math.exp(-dt*9));camera.lookAt(focus);if(started)updateHud(now);renderer.render(scene,camera);requestAnimationFrame(frame)}frame();

